variable "project_name" {}
variable "image_id" {}
variable "vpc_cidr" {}
variable "public_subnet_1a" {}
variable "public_subnet_1b" {}
variable "public_subnet_1c" {}
variable "private_subnet_1a" {}
variable "private_subnet_1b" {}
variable "load_balancers_arn" {}
variable "load_balancers" {}